import type { Metadata } from "next";
import "./globals.css";

const firaCode = {
  subsets: ['latin'],
  variable: '--font-fira-code',
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
      <link
          href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${firaCode.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
